### PR TITLE
Nested routes in accounts and addressbook

### PR DESCRIPTION
**Pull request by yacare555**
https://gitcoin.co/issue/vue-polkadot/apps/82/4509

### CODE REVIEW

**Comment by yangwao** [comment]
Bugs I found
- When I add a new account
image

- When I add new contact
image

Otherwise looks mergeable :)

**Review by yangwao — CHANGES_REQUESTED** [review]
Found errors when adding account or contact

**Comment by yangwao** [comment]
We are developing KodaDot as a mobile-first experience.
I think modal is good, but whenever you are on mobile, this is no-go in our philosophy 

image

**Comment by yacare555** [comment]
Hi @yangwao , I've changed modal for mobile-first experience instead,
The error is not related to this implementation, it's related to the tags array property, I've also fixed it.

Btw, I saw that this two bounties have been "Warned for Abandonment of Bounty" many times  with no progress, I'd like to work on this two as well if it's possible.
https://gitcoin.co/issue/vue-polkadot/apps/99/4510
https://gitcoin.co/issue/vue-polkadot/apps/76/4508

**Comment by yangwao** [comment]
As you force pushed, GH utility doesn't work now 
image
whatever
 https://github.com/cli/cli/issues/562

**Comment by yangwao** [comment]
Ok, it's a building and it's working w/o errors. Merging

**Pull request merged**
