### PR TITLE
Use named routing and nested routes in accounts and addressbook with warnings fixed

### PR DESCRIPTION
**Pull request by Devilla**

### CODE REVIEW

**Comment by yangwao** [comment]
I struggle to see Nested routes https://router.vuejs.org/guide/essentials/nested-routes.html

**Review by yangwao — APPROVED** [review]
I struggle to find Nested Routes :)

**Review by yangwao — CHANGES_REQUESTED** [review]
I struggle to find Nested Routes

**Comment by Devilla** [comment]
> I struggle to find Nested Routes

Let me check and update.

**Comment by Devilla** [comment]
- Nested Routes will show nested components is it okay?

1. http://127.0.0.1:9090/#/accounts/create

image

2. http://127.0.0.1:9090/#/accounts/restore

image

**Comment by Devilla** [comment]
@yangwao please review and update

**Comment by yangwao** [comment]
Thank you for your time, already merged https://github.com/vue-polkadot/apps/pull/117

**Pull request closed without merging**
