### PR TITLE
fix: denomination step values

### LINKED ISSUE #63: Denomination and formatting
We've got `formatBalance.ts` which does some small amount of magic.

Inspiration could be found here https://github.com/polkadot-js/common/blob/master/packages/util/src/format/formatBalance.ts

Right now we are struggling to allocate time on this and rather make this as bounty.

- [ ] fix all the use cases in code right now which are using the denomination
- [ ] repair components which are not using the denomination or not using denomination at all

Would be nice to follow and cover cases like this
image

### PR DESCRIPTION
**Pull request by Ryan-Gordon**
Investigating the issue where a user cannot select denominations of denominations i.e 0.1 milli or 0.01 whole.

The problem was coming from the b-input tag and it did not have any value for step. Without a value the range is whole numbers.
Added a step with 3 decimal places as that is what is being used in formatBalance.
This in turn removes the formatting issue.
Fixes vue-polkadot/apps#63
After verfiying the fix makes the problem go away I went to search for other components which use it and found only 1 in the Amount component.

### CODE REVIEW

**Comment by yangwao** [comment]
Just made comments in the issue https://github.com/vue-polkadot/apps/issues/63#issuecomment-640592048 :)

**Comment by yangwao** [comment]
You should merge develop branch to be up to date, I can't test your PR against Kusama test :)

Also, please make PR against develop branch.

**Comment by Ryan-Gordon** [comment]
Thats on me I should I have changed base branch here also when I changed it in the other branch/pr 
Have merged develop branch into this one and changed the base. All Checks seem to pass so I think it is ready for testing 🚀 
Let me know if something creeps up or needs changing. 👍

**Comment by yangwao** [comment]
Looks like you've did not merged the latest develop branch. 
Latest have these packages
image

But you have some older one https://github.com/vue-polkadot/apps/commit/785184dc28d22f8952a3f82486a7646cac15ba21

Can't connect on Kusama with your PR, can't test, I've tried to adjust to the latest one, doesn't work.

Please merge most latest develop branch, in Kusama things changes and breaks every day :)

**Comment by Ryan-Gordon** [comment]
I think the problem was I am working on a fork and I didn't merge upstream/develop. 
Done this now and branch is at edb2c2b

**Comment by yangwao** [comment]
👌
image

**Comment by Ryan-Gordon** [comment]
Glad to hear it’s looking good! Thank you for reviewing/testing and dealing with my merge issue for this PR @yangwao I appreciate your time. 🚀

**Comment by yangwao** [comment]
You are welcome :)

**Pull request merged**
