### PR TITLE
Named Routing in router.ts

### PR DESCRIPTION
**Pull request by Devilla**
Let me know if you wanted something like this for Named Routes so I can continue further.

### CODE REVIEW

**Comment by vikiival** [comment]
Please leave routes as async

**Comment by Devilla** [comment]
@vikiival okay but what's its purpose, is it necessary?

**Comment by vikiival** [comment]
```
JavaScript bundle can become quite large, and thus affect the page load time.
It would be more efficient if we can split each route's components into a separate chunk,
and only load them when the route is visited
``` 
Source: 
https://router.vuejs.org/guide/advanced/lazy-loading.html#grouping-components-in-the-same-chunk

**Comment by Devilla** [comment]
Okay got it. Also, which are the named routing aren't working for you because I checked a few they're working locally.

**Pull request closed without merging**
